title: Converting Media Files
hero_image: images/banner.png
subtitle: rpi-converting-audio-files subtitle
description: Convering media files with avconv
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Converting Media Files
